theme: jekyll-theme-cayman
title: "Seminários de Machine Learning,<br>Geometria e Topologia"
description: Neste site contaremos com as descrições, datas e links dos seminários organizados pelo grupo de Geometria do IME USP.
