theme: jekyll-theme-cayman
title: Seminários de Machine Learning e Matemática
description: Para melhor organização, neste site contaremos com as descrições, datas e links dos seminários organizados pelo grupo de Geometria do IME USP.
